# Generated by Django 3.2.5 on 2023-02-21 21:56

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(blank=True, default='Ye.S', max_length=10, null=True, verbose_name='作者')),
                ('desc', models.CharField(max_length=50, verbose_name='简要描述')),
                ('cover', models.URLField(default='https://i.loli.net/2020/04/23/lJLjEtbs2NFwynQ.jpg', verbose_name='页面横幅')),
                ('portfolio_icon', models.CharField(default='fas fa-envelope', max_length=50, verbose_name='归档页图标')),
                ('content', mdeditor.fields.MDTextField(verbose_name='详细内容')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '介绍',
                'verbose_name_plural': '介绍',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TidalPrediction', max_length=30, verbose_name='网站名字')),
                ('keywords', models.CharField(default='关键字测试', max_length=50, verbose_name='网站关键词')),
                ('desc', models.CharField(max_length=50, verbose_name='网站描述')),
                ('slogan', models.CharField(max_length=50, verbose_name='网站标语')),
                ('icp_number', models.CharField(max_length=40, verbose_name='备案号')),
                ('icp_url', models.URLField(default='http://www.beian.miit.gov.cn/', max_length=100, verbose_name='备案链接')),
                ('index_banner', models.URLField(default='https://s2.loli.net/2022/01/03/XJgetwVDfanWPMk.jpg', max_length=100, verbose_name='首页横幅')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
