# Generated by Django 3.2.5 on 2023-02-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=100, verbose_name='appId')),
                ('appkey', models.CharField(max_length=100, verbose_name='appKey')),
                ('avatar', models.CharField(blank=True, default='', max_length=100, verbose_name='发帖形象')),
                ('pagesize', models.IntegerField(default='10', verbose_name='pageSize')),
                ('placeholder', models.CharField(max_length=100, verbose_name='占位描述')),
            ],
            options={
                'verbose_name': 'valine评论',
                'verbose_name_plural': 'valine评论',
            },
        ),
    ]
